routes/ruta.py
from flask import Blueprint, flash, render_template, request, url_for, redirect, flash, session, jsonify, make_response
#from app import socketio, emit
# from flask_wtf.csrf import CSRFProtect
from Models.datemysql import User, User_Type, Employees, Binnacle
#from Models.date import Usuario, Empleados, Bitacora, Tipo_User
from db import db
from static.dicionario import *



ruta = Blueprint('ruta', __name__)
# csrf = CSRFProtect()

# notificaciones

"""
@socketio.on('event')
def event(json):
    print("Estamos de prueba"+json)
    emit('event', json) 
"""

@ruta.route("/notificaciones")
def notificaciones():
    return render_template('noti.html')

#Rutas_del_FrontEnd

@ruta.route("/")
def principal():
    return render_template('FrontEnd/index.html')

@ruta.route("/porque")
def porque():
    return render_template('FrontEnd/porque.html')

# funcion de session
def verificar_sesion():
    return 'prueba' in session

# rutas de emails
@ruta.route("/registro")
def registro():
    if verificar_sesion():
        #tipo_usuario = Tipo_User.query.all()
        user_Type = User_Type.query.all()
        return render_template('auth/registro.html', user_Type=user_Type)
    else:
        mensaje = "Lo siento, debes iniciar sesión para acceder a esta página."
        return render_template('mensaje.html', mensaje=mensaje)
# ingreso de los datos del formulario de email


@ruta.route("/Datos", methods=['POST'])
def vacio2():
  
        """name = request.form['usuario']
        name2 = request.form['password']
        name3 = request.form['id_tipo_usuario']"""
        name = request.form['email']
        name2 = request.form['password']
        name3 = request.form['User_Type_id_User_Type']
        me = User(name, name2,name3)
        #me = Usuario(name, name2,name3)
        db.session.add(me)
        db.session.commit()
        return redirect(url_for("ruta.admin"))


@ruta.route("/actualizar/<id>", methods=['GET', 'PUT'])
def actualizar(id):
    if verificar_sesion(): 
        #datos = Usuario.query.get(id)
        #tipo_usuario = Tipo_User.query.all()
        datos = User.query.get(id)
        user_Type = User_Type.query.all()
        if request.method == "GET":
            return render_template('auth/actualizar.html', datos=datos, user_Type=user_Type)
        req = request.get_json()
        if request.method == "PUT":
            datos.email = req['email']
            datos.password = req['password']
            datos.User_Type_id_User_Type = req['User_Type_id_User_Type']
            
            db.session.commit()

            return redirect(url_for("ruta.admin"))
    else:
        return render_template('mensaje.html')


@ruta.route("/Eliminar/<id>",methods=['DELETE'])
def Eliminar(id):
    if verificar_sesion() and request.method == 'DELETE':  
        #eliminar = Usuario.query.get(id)
        eliminar = User.query.get(id)    
        if eliminar:
            db.session.delete(eliminar)
            db.session.commit()

        return redirect(url_for("ruta.admin"))
    else:
        return render_template('mensaje.html')

# rutas de empleados

@ruta.route("/RegistroE")
def RegistroE():
    if verificar_sesion():    
        #id_email = Usuario.query.all()
        email = User.query.all()
        return render_template('auth/RegistroEmpleado.html', email=email)
    else:
        return render_template('mensaje.html')
# ingreso de los datos de empleados
@ruta.route("/empleado", methods=['POST'])
def registro_empleado():
    if verificar_sesion():    
        """
        dato_empleado0 = request.form['nombre']
        dato_empleado1 = request.form['rfc']
        dato_empleado2 = request.form['direccion']
        dato_empleado3 = request.form['grado_estudio']
        dato_empleado4 = request.form['edad']
        dato_empleado5 = request.form['puesto']
        dato_empleado6 = request.form['id_empleado']
        """
        dato_empleado0 = request.form['name']
        dato_empleado1 = request.form['rfc']
        dato_empleado2 = request.form['adress']
        dato_empleado3 = request.form['study_grade']
        dato_empleado4 = request.form['age']
        dato_empleado5 = request.form['position']
        dato_empleado6 = request.form['correo']

        #me = Empleados(dato_empleado0, dato_empleado1, dato_empleado2, dato_empleado3,
                    #dato_empleado4, dato_empleado5, dato_empleado6)
        
        me = Employees(dato_empleado0, dato_empleado1, dato_empleado2, dato_empleado3,
                    dato_empleado4, dato_empleado5, dato_empleado6)
        db.session.add(me)
        db.session.commit()

        return redirect(url_for("ruta.admin"))
    else:
        return render_template('mensaje.html')

@ruta.route("/actualizar_empleado/<id>", methods=['GET', 'PUT'])
def actualizar_empleados(id):
    if verificar_sesion():    
        datos = Employees.query.get(id)
        if request.method == "GET":
            
            
            return render_template('auth/actulizar_empleados.html', datos=datos)

        req = request.get_json()
        if request.method == "PUT":
            
            
            datos.name = req['name']  
            datos.rfc = req['rfc']
            datos.adress = req['adress']
            datos.study_grade = req['study_grade']
            datos.age = req['age']
            datos.position = req['position']
            
            db.session.commit()
            
            return redirect(url_for("ruta.admin"))
    
    else:
        return render_template('mensaje.html')


  


@ruta.route("/Eliminarempleado/<id>",methods=['DELETE'])
def Eliminar_empleado(id):
    if verificar_sesion() and request.method == 'DELETE':       
        eliminar = Employees.query.get(id)
        if eliminar:    
            db.session.delete(eliminar)
            db.session.commit()

        return redirect(url_for("ruta.admin"))
    else:
        return render_template('mensaje.html')
@ruta.route("/entrar")
def entrar():
    datos = User.query.all()
    if request.method == 'GET':
        return render_template('login.html',datos=datos)

# Login
@ruta.route("/acceso", methods=['GET', 'POST'])
def acceso_al_sistema():
   
    if request.method == 'GET':
        return render_template('FrontEnd/login.html')

    name = request.form['usuario']
    name2 = request.form['password']
    if request.method == 'POST':
        me = db.session.query(User).filter_by(
            email=name, password=name2).first()

    if (me != None):
        session['prueba'] = name
        session['id_user'] = me.id_user
        if (me.User_Type.id_User_Type == 1):
            flash(Mensaje_admin, 'succes')
            return redirect(url_for("ruta.admin"))
        elif (me.User_Type.id_User_Type == 2):

            return redirect(url_for("ruta.bit"))
        else:

            print("hubo algun error")
    else:
        flash(Login_crediciales, 'warning')
        return redirect(url_for("ruta.acceso_al_sistema")),me


@ruta.route("/admin", methods=['GET', 'POST', 'PUT','DELETE'])
def admin():
    datos_empleado = Employees.query.all()
    user = User.query.all()
    bit = Binnacle.query.all()
    if 'prueba' in session:   
           
            return render_template('auth/ultima.html', datos_empleado=datos_empleado, user=user,bit=bit)

    else:
        return render_template('mensaje.html')

 # sistema de logout
@ruta.route("/logout")
def logout():
    session.clear()
    flash(Logout, 'success')
    return redirect(url_for("ruta.acceso_al_sistema"))

# rutas de bitacora


@ruta.route("/bitacora")
def bit():
        if verificar_sesion():   
            id_user = session.get('id_user')
            if id_user is not None:
                dato_bit = Binnacle.query.all()
                usuario = User.query.get(id_user)
            
                return render_template("auth/pagina_Bitacora.html",usuario=usuario,dato_bit=dato_bit)
        else:
            return render_template('mensaje.html')

@ruta.route("/registro_bitacora", methods=['POST'])
def registro_bitacora():

    if verificar_sesion():   
        name = request.form['log_data']
        name2 = request.form['comments']
        id = request.form['User_id_User']

        me = Binnacle(name, name2, id)
        db.session.add(me)
        db.session.commit()

        return redirect(url_for("ruta.bit"))
    else:
        return render_template('mensaje.html')


@ruta.route("/actualizar_bitacora/<id>", methods=['GET', 'PUT'])
def actualizar_bitacora(id):
    if verificar_sesion(): 
        datos = Binnacle.query.get(id)

        if request.method == "GET":
            return render_template('auth/actualizar_bitacora.html', datos=datos)
        req = request.get_json()
        if request.method == "PUT":

            datos.log_data = req['log_data']
            datos.comments = req['comments']
            db.session.commit()
            return redirect(url_for("ruta.admin"))
            
    else:
        return render_template('mensaje.html')


@ruta.route("/Eliminarbitacora/<id>",methods=['DELETE'])
def Eliminar_bitacora(id):
    if verificar_sesion() and request.method == 'DELETE':   
        eliminar = Binnacle.query.get(id)
        if eliminar:   
            db.session.delete(eliminar)
            db.session.commit()

        return redirect(url_for("ruta.admin"))
    else:
        return render_template('mensaje.html')

templates/FrontEnd/index.html
{% extends './FrontEnd/layaut.html' %}
<!--Pagina de principal(index) de la FrontEnd-->

{% block title %}Bievenido{% endblock %}

{% block customCSS %}

<link rel="stylesheet" href="{{ url_for ('static' , filename='css/index.css')}}">

{% endblock %}

{% block body %}

<!-- div para contener las carta de imagenes-->
<div class="container">
  <div class="title-container">
    <h1>Proyecto Bitácora</h1>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="card">
        <img class="card-img-top" src="static/img/bitacora1.jpg" alt="Imagen 1">
        <div class="card-body">
          <h5 class="card-title">La importancia de las bitácoras</h5>
          <p class="card-text">Descubre por qué las bitácoras son esenciales para el seguimiento y registro de actividades en proyectos y tareas.</p>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card">
        <img class="card-img-top" src="static/img/bitacora2.jpg" alt="Imagen 2">
        <div class="card-body">
          <h5 class="card-title">Optimiza tu tiempo con una bitácora</h5>
          <p class="card-text">Aprende cómo una bitácora puede ayudarte a gestionar y aprovechar mejor tu tiempo, aumentando tu productividad.</p>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card">
        <img class="card-img-top" src="static/img/bitacora3.jpg" alt="Imagen 3">
        <div class="card-body">
          <h5 class="card-title">Bitácoras: una herramienta indispensable</h5>
          <p class="card-text">Descubre por qué las bitácoras son una herramienta esencial en la planificación y seguimiento de proyectos a largo plazo.</p>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="card">
        <img class="card-img-top" src="static/img/bitacora4.jpg" alt="Imagen 4">
        <div class="card-body">
          <h5 class="card-title">Registro detallado y análisis</h5>
          <p class="card-text">Aprende cómo el registro detallado en una bitácora te permite realizar un análisis exhaustivo de tus actividades y progresos.</p>
        </div>
      </div>
    </div>
    <div class="col-md-4">
    <div class="card">
    <img class="card-img-top" src="static/img/bitacora5.jpg" alt="Imagen 5">
    <div class="card-body">
    <h5 class="card-title">Bitácoras y colaboración en equipo</h5>
    <p class="card-text">Descubre cómo las bitácoras facilitan la colaboración y comunicación efectiva entre los miembros de un equipo de trabajo.</p>
    </div>
    </div>
    </div>
    <div class="col-md-4">
    <div class="card">
    <img class="card-img-top" src="static/img/bitacora6.jpg" alt="Imagen 6">
    <div class="card-body">
    <h5 class="card-title">Seguimiento del progreso y metas</h5>
    <p class="card-text">Aprende cómo las bitácoras te permiten realizar un seguimiento efectivo de tu progreso y alcanzar tus metas de manera más eficiente.</p>
    </div>
    </div>
    </div>
    </div>
    
      </div>

  
{% endblock %}

templates/FrontEnd/layaut.html
<!DOCTYPE html>
<!-- El layaut del FrontEnd-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="shortcut icon " href="{{ url_for ('static' , filename ='img/logo.svg')}}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
   
    
    {% block customCSS %}
       {% endblock %}
       <!--Codigo del Menu : Tecnologia boostrap 5-->
       <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand"  style="margin: 5px;">
            <img src="{{ url_for('static', filename='img/logo.svg')}}" alt="Logo de SIGSA" class="navbar-image">
          </a>
      
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
      
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mx-auto">
              <li class="nav-item" style="margin: 5px;">
                <a class="nav-link" href="/">
                  <i class="fas fa-home fa-lg"></i>
                  <div>Bienvenidos</div>
                </a>
              </li>
              <li class="nav-item" style="margin: 5px;">
                <a class="nav-link" href="{{ url_for('ruta.porque')}}">
                  <i class="fas fa-question-circle fa-lg"></i>
                  <div>Why</div>
                </a>
              </li> 
              <li class="nav-item" style="margin: 5px;">
                <a class="nav-link" href="{{url_for('ruta.acceso_al_sistema')}}">
                  <i class="fas fa-sign-in-alt fa-lg"></i>
                  <div>Iniciar Sesión</div>
                </a>
              </li>
            </li> 
            </ul>
          </div>
        </div>
      </nav>
    
      <!-- Codigo de estilo del menu -->
      <style>
        .navbar-image {
          height: 60px;
          margin-right: 10px;
          object-fit: contain;
        }
      
        .nav-link {
          display: flex;
          flex-direction: column;
          align-items: center;
        }
      
        .nav-link div {
          font-size: 14px;
        }
        .nav-link i {
          margin-bottom: 5px;
        }
      </style>
    
</head>
<body>
  

 






 


        {% block body %}
        
        {% endblock %}
    
    <!-- Cdn de jquery-->
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    
    <!-- Popperjs cdn para las interaciones de la pagina web de javascript-->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    
    <!-- Cdn de la tecnologia boostrap 5 beta-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
    
    <!-- Cdn de axion mas funicones de javascript-->
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    
    {% block customJS %}
      {% endblock %}
</body>

<!-- Footer -->
  <footer class="text-center text-lg-start bg-light text-muted">
    <!-- Section: Social media -->
    <section
      class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
      <!-- Left -->
      <div class="me-5 d-none d-lg-block">
        <span>Redes de ?:</span>
      </div>
      <!-- Left -->

      <!-- Right -->
      <div>
        <a href="https://www.facebook.com/" class="me-4 text-reset">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="https://twitter.com/" class="me-4 text-reset">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="https://www.youtube.com/" class="me-4 text-reset">
          <i class="fa-brands fa-youtube"></i>
        </a>
        <a href="https://www.instagram.com/" class="me-4 text-reset">
          <i class="fab fa-instagram"></i>
        </a>
        <a href="https://www.linkedin.com/" class="me-4 text-reset">
          <i class="fab fa-linkedin"></i>
        </a>
        <a href="https://github.com/inerxd?tab=repositories" class="me-4 text-reset">
          <i class="fa-brands fa-square-github"></i>
        </a>
      </div>
      <!-- Right -->
    </section>
    <!-- Section: Social media -->

    <!-- Section: Links  -->
    

    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
      © 2022-2023 Copyright:
      <a class="text-reset fw-bold" >Enterprise Javier</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->
  
  </html>

templates/FrontEnd/login.html
{% extends './FrontEnd/layaut.html' %}
{% block title %}Login{% endblock %}
{% block customCSS %}
<link rel="stylesheet" href="{{ url_for ('static' , filename='css/login.css')}}">
{% endblock %}


{% block body %}

<form class="form-signin"  name="myForm" action="{{ url_for('ruta.acceso_al_sistema') }}" method="POST">
    <img class="mb-4" src="{{ url_for ('static' , filename ='img/logo.svg')}}" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">INICIAR SESION</h1>

    <div class="form-floating mb-3">
      <input type="email" class="form-control" id="usuario" name="usuario" placeholder="name@example.com">
      <label for="floatingInput">Email address</label>
    </div>
    <div class="input-group mb-3">
      <input type="password" class="form-control form-control-md" id="password" name="password" placeholder="Password">
      <button  class="btn-lg btn-light" style="margin: 1%;"  type="button" onclick="mostrarOcultarContrasena()">
        <span id="iconoMostrarOcultar" ><i class="fas fa-eye"></i></span> 
      </button>
    </div>
   

    
    <button class="w-100 btn btn-lg btn-primary" type ="submit" id="prueba" style="margin:1% ;">Login</button>
    {% with messages = get_flashed_messages(with_categories=True) %}

    {% if messages %}
    
    {%for category,message in messages %}
    
    {% if category == 'warning' %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <strong>{{message}}</strong> 
      <button type="button" class="btn-close" data-bs-dismiss="alert"   aria-label="Close"></button>
    </div>
    {% else %}
    <div class="alert alert-success alert-dismissible fade show"  role="alert">
      <strong>{{message}}</strong> 
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>

    {% endif %}

    {% endfor %}
    {% endif %}
    {% endwith %}

  </form>

  {% block customJS %}
  <script src="{{ url_for('static',filename='js/login.js') }}"></script>
  <script src="{{ url_for('static',filename='js/visualizar_password.js') }}"></script>
  {% endblock %}
{% endblock %}

templates/FrontEnd/mensaje.html
<!DOCTYPE html>
<html>
      <!-- Mensaje de error de sesion -->
<head>
    <!-- Titulo del error-->>
    <title>Error - Debes Iniciar Sesión</title>
    <!--Estilo de visualisacion del error-->
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            background-color: #f2f2f2;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }

        h1 {
            color: #ff0000;
        }

        img {
            width: 300px;
            margin-top: 20px;
        }

        p {
            font-size: 18px;
            margin-top: 20px;
            color: #333;
        }
    </style>
</head>
<body>
    <!-- Titulo de error de inicio de session-->>
    <h1>Error - Debes Iniciar Sesión</h1>
    <!--Imagen para el error de session-->>
    <img src="{{ url_for ('static' , filename ='img/error_session.png')}}" alt="Error Image">
    <!-- Mensaje de error de session-->>
    <p>Lo siento, debes iniciar sesión para acceder a esta página.</p>
</body>
</html>

templates/FrontEnd/noti.html
<!DOCTYPE html>
<!-- pagina en construcion de alertas(por el momento no hace nada)-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>socketIO</title>
    <script src="https://cdn.socket.io/4.6.0/socket.io.min.js" integrity="sha384-c79GN5VsunZvi+Q/WObgk2in0CbZsHnjEqvFxC5DxHn9lTfNce2WW6h2pH6u/kF+" crossorigin="anonymous"></script>
</head>
<body>
     <button onclick="sendmsm()">click</button>
    <h1>hola mundo</h1>
    <script>
        var socket = io()

        function sendmsm(){
          socket.emit('event','hola wey')
        }
        socket.on('connect',function(){
            console.log("conectado!")
        })
        socket.on('event',function(res){
            console.log("event"+res)
        })



        socket.on('disconnect',function(){
            console.log("desconectados!")
        })

    </script>

  
</body>
</html>

templates/FrontEnd/porque.html
{% extends './FrontEnd/layaut.html' %}
<!--Pagina de relleno-->>
{% block title %}Informacion Bitacora{% endblock %}
{% block customCSS %}
<link rel="stylesheet" href="{{ url_for ('static' , filename='css/xq.css')}}">
{% endblock %}
{% block body %}
<body>
	<div class="container">
		<h1>El Tiempo</h1>
		<p>El tiempo es un recurso muy escaso e irremplazable, incluso podríamos decir que indefinible. Es intangible, no podemos variarlo, retrocederlo o adelantarlo. Los seres humanos comprendemos y utilizamos el tiempo como una medida que nos permite situar algo sobre una línea cronológica para expresar cambios entre dos momentos determinados. En consecuencia, igual que cualquier escala de medición, la manera en que lo calculamos es un invento del hombre. De hecho, tenemos la noción de cuán importante es y para medirlo en cuestión de minutos y segundos, necesitamos relojes. Con ellos podemos auto examinarnos y tener una herramienta práctica para su manejo. Sin embargo, a pesar de buscar formas de medir el tiempo, su desperdicio es un mal que afecta mucha gente. A pesar de que cada nuevo día el tiempo es repartido equitativamente y que todos tenemos la misma cantidad, a algunas personas no les alcanza, para otras es justo el que necesitan y a otras pareciera que les sobra, entonces lo malgastan. Lo que pasa es que, aunque todos sabemos que el tiempo es transitorio, no para todos transcurre con la misma velocidad ni de la misma manera.</p>
    <img src="https://www.w3schools.com/w3images/fjords.jpg" alt="Pasando el tiempo">
		<br>
    <h1>La bitacora</h1>
    <p>
      Una bitácora es un registro de eventos, generalmente en orden cronológico, que puede incluir detalles sobre una actividad específica o sobre un determinado proceso. En muchos casos, las bitácoras se utilizan para rastrear el progreso de un proyecto o para documentar los pasos realizados durante un experimento o una investigación.
      Características de una bitácora:
      Registra eventos en orden cronológico.
      Puede incluir detalles sobre una actividad específica o sobre un determinado proceso.
      Se utilizan para rastrear el progreso de un proyecto o para documentar los pasos realizados durante un experimento o una investigación.
      ¿Qué importancia tiene una bitácora?​
      La importancia de una bitácora radica en que permite hacer un seguimiento de un proyecto o actividad, y así poder detectar errores o problemas a tiempo. También sirve como documentación para futuras referencias.
    </p>
    <img src='/static/img/bitacora.jpg' alt="Bitácora">
	</div>
</body>

 
  
{% endblock %}